//estos sirven para describir que pasa en mi aplicacion
export const AGREGAR = 'AGREGAR';
export const AGREGAR_EXITO = 'AGREGAR_EXITO';
export const AGREGAR_ERROR = 'AGREGAR_ERROR';

export const COMENZAR_DESCARGA = 'COMENZAR_DESCARGA';
export const DESCARGA_EXITO = 'DESCARGA_EXITO';
export const DESCARGA_PROVEEDOR_EXITO = 'DESCARGA_PROVEEDOR_EXITO'
export const DESCARGA_CIENTE_EXITO = 'DESCARGA_CIENTE_EXITO';
export const DESCARGA_VENTAS_EXITO = 'DESCARGA_VENTAS_EXITO';
export const DESCARGA_COMPRAS_EXITO = 'DESCARGA_COMPRAS_EXITO';
export const DESCARGA_ERROR = 'DESCARGA_ERROR';

export const OBTENER_ELIMINAR = 'OBTENER_ELIMINAR';
export const ELIMINADO_EXITO = 'ELIMINADO_EXITO';
export const ELIMINADO_ERROR = 'ELIMINADO_ERROR';

export const OBTENER_EDITAR = 'OBTENER_EDITAR';
export const COMENZAR_EDICION = 'COMENZAR_EDICION';
export const EDITADO_EXITO = 'EDITADO_EXITO';
export const EDITADO_ERROR = 'EDITADO_ERROR';



// REDUCERS DE ALERTA
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

// Listas
export const AGREGARLISTAPROVEEDOR = 'AGREGARLISTAPROVEEDOR';


